version: '3'
services:
  indexcast:
    image: ermak/indexcast:1.0.0
    container_name: indexcast_container
    volumes:
    - ../migration-schema.yml:/indexcast/configs/migration-schema.yml
    environment:
      - THREADS=4
      - PER_CYCLE=5000
      - QUERY=*:*
      - SCHEMA_PATH=/indexcast/configs/migration-schema.yml
      - SRC_SOLR_HOST=http://localhost:8983
      - SRC_CORE_NAME=solr/test_src_core
      - DST_SOLR_HOST=http://localhost:8984
      - DST_CORE_NAME=solr/test_dst_core
      - LOGGING_LEVEL_CZ_MZK=DEBUG
